language: python
cache: pip
dist: xenial

install:
 - pip install --upgrade pip setuptools
 - pip install tox-travis

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"

env:
  - TWISTED="16"
  - TWISTED="latest"

script:
  - tox

matrix:
  include:
    - python: "3.5"
      env: TOXENV=lint3

notifications:
  email: false
